version: '3.4'

services:
    reverseproxy:
        image: nginx:alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8084:8084
        restart: always

    mvc:
        depends_on:
            - reverseproxy
        image: mvc
        restart: always